language: node_js
node_js:
- '4.2'
env:
  global:
  - DEPLOY_BRANCH=master
  - secure: RU2BCe1MLVOEP+S86UzTegpprMJ7O/MlhIm0ZM/t82M7FwbzcC7mx0X+GeXJoyRU/cP5T9YEKAKr0cpd2v0qe3PcBoDcSB/pHO4pB/FrdEfMt6o0iVAr2NoOtulL4txVs3Eo6yxicTBCwwjtLnfHwsAoO+a9fw3UFZN53WARrBAT5hWz0BdjD6bMyA1/M74uxeUI9CtC2IajMKl9f/LZgWdb80/On2SM5kAxXJrP6Z8v2fLARH5cqtqLz9z/2avDxKXtKla5Qg/2tca5CXNf2GqCYXIDjbFQ1e7nUBpM2a7EvA//a96M3kLVhbHiHBjpPr7fJYgtyrdvwQGlEhAJrSNwec/4e+FW7bg7qShpvYnloTMRq17uKe9upN4vJcqiWZYCnw2SygMMHhNBz5ZwHKtfIFi2ZKRjxVbbSzRqM+zdxlERdxWYjhD/nibG3vbkya/RgC806h3NyKhkuHyZWFN5ylRc+Q59WmosJYlOf5Gg9QS9CQzKuUgQ9Nq/vT5LmbEb0Wa1LmxaiGfk/DNZ0tfUwDr7TSZz71kIO5DfHo4f9x+sK168ip0VUVLmTEc2Qx0kHC8hsdf4prxkLxQ9owpqKEr7sFGe7UvuCBqE3w6EmttqYRvq2boZnKFIhC27wqfLs+q/MDCSkb3O+1P13fAWw4NGRFYR94qMadKO/sA=
cache:
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/precalc.js
before_script:
- npm test
- node ./.build_scripts/precalc.js
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
